version: '3.7'

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: ''
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    networks:
      pihole_network:
        ipv4_address: 172.21.0.2
        ipv6_address: fd00::2

  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest #Raspi
    volumes:
      - ./unbound:/opt/unbound/etc/unbound
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
    healthcheck:
      test: ["NONE"]
    restart: unless-stopped
    networks:
      pihole_network:
        ipv4_address: 172.21.0.3
        ipv6_address: fd00::3

networks:
  pihole_network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.0/24"
        - subnet: "fd00::/64"
